BUSN:5760 Applied Business Statistics <br>
Assignment 1: Data Wrangling With Pandas

In [1]:
#1)	Import Pandas and assign it the alias pd
import pandas as pd

In [2]:
#2)	Load “grades.csv” into a Pandas dataframe called “df1”
df1 = pd.read_csv('C:/Users/rupas/Desktop/Applied Business Statistics/Python4Statistics/Stuff For Class/Homework Assignments/Assignment 1/grades.csv')
df1

     ID                 Name   GPA              Major
0    23            Rose Rios  3.97          Economics
1    55            Ian Brown  1.44  Political Science
2    54         Stanley Dean  3.75         Philosophy
3    19  Stephanie Henderson  1.86        Mathematics
4    81          Angela Mora  3.86            Physics
..   ..                  ...   ...                ...
97   41     Brenda Valentine  3.10            Physics
98   86        Grace Hoffman  1.30          Chemistry
99   10          Joshua Ware   NaN            English
100  61      Samantha Steele  2.56            Spanish
101  22            Lisa Chen  1.45                Art

[102 rows x 4 columns]

In [3]:
#3)	Display the top 10 rows of data
print(df1.head(10))

   ID                 Name   GPA              Major
0  23            Rose Rios  3.97          Economics
1  55            Ian Brown  1.44  Political Science
2  54         Stanley Dean  3.75         Philosophy
3  19  Stephanie Henderson  1.86        Mathematics
4  81          Angela Mora  3.86            Physics
5  60          Mark Martin  1.47          Chemistry
6  47     Jennifer Perkins  2.88            English
7  11      William Stewart  1.27            Biology
8  34           Eric Moore  3.40            Spanish
9  70      Kenneth Rollins  2.37                Art

In [4]:
#4)	Display the bottom 10 rows of the data
print(df1.tail(10))

     ID                   Name   GPA        Major
92   72            Joseph Beck  1.56      Spanish
93   18        Alexandra Green  3.12          Art
94   65  Christopher Hernandez  2.08      History
95   78       William Caldwell   NaN   Philosophy
96   20            Diane Brown  1.73  Mathematics
97   41       Brenda Valentine  3.10      Physics
98   86          Grace Hoffman  1.30    Chemistry
99   10            Joshua Ware   NaN      English
100  61        Samantha Steele  2.56      Spanish
101  22              Lisa Chen  1.45          Art

In [5]:
#5)	Display a table of the variable names, as well as their associated counts and data types
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      102 non-null    int64
 1   Name    102 non-null    object
 2   GPA     99 non-null     float64
 3   Major   101 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 3.3+ KB

In [6]:
#6)	Display basic summary statistics for the dataset’s numerical variables
# Summary Statistics
df1.describe()

               ID        GPA
count  102.000000  99.000000
mean    50.392157   2.471919
std     29.531710   0.818628
min      1.000000   1.030000
25%     24.250000   1.815000
50%     50.500000   2.460000
75%     75.750000   3.145000
max    100.000000   3.970000

In [7]:
#7)	Check for duplicate rows and display them if they exist
duplicates = df1.duplicated()
print(duplicates)

#View instances of the duplicated rows
duplicated_rows = df1[df1.duplicated()]
print(duplicated_rows)

0      False
1      False
2      False
3      False
4      False
       ...
97     False
98     False
99     False
100    False
101    False
Length: 102, dtype: bool
     ID                Name   GPA    Major
58   15           Lisa Chen  2.05      Art
81  100  Lawrence Rodriguez  2.66  Theatre
90   17     Alexandra Green  2.46  History

In [8]:
#8)	Drop any duplicate rows from the dataset and redisplay duplicate rows to check that they’ve been removed
#Drop duplicate rows
df1.drop_duplicates(inplace=True)

#Duplicates are now gone
duplicated_rows = df1[df1.duplicated()]
duplicated_rows

Empty DataFrame
Columns: [ID, Name, GPA, Major]
Index: []

In [9]:
#9)	Check for rows with missing values and display them if they exist
#Count missing values, display rows with missing values, and drop rows with missing values
print(df1.isnull().sum())

missing_data = df1[df1.isna().any(axis=1)]
print(missing_data)

ID       0
Name     0
GPA      3
Major    1
dtype: int64
    ID              Name   GPA       Major
64  49         Judy Hunt   NaN     English
87  29  Jonathan Coleman  1.66         NaN
95  78  William Caldwell   NaN  Philosophy
99  10       Joshua Ware   NaN     English

In [10]:
#10)	 Drop any rows with missing values from the dataset and redisplay the rows with missing values to check that they’ve been removed  
df1.dropna(inplace=True)#inplace true modifies the existing data frame
print(df1.isnull().sum())

ID       0
Name     0
GPA      0
Major    0
dtype: int64

In [11]:
#11) Create a column called “Honor Student” and put a “Yes” if their GPA exceeds 3.5 and a “No” if it doesn’t.  Use a custom function and the map function

df1['Honor Student'] = df1["GPA"].apply(lambda x: 'Yes' if x > 3.5 else 'No')
df1

     ID                 Name   GPA              Major Honor Student
0    23            Rose Rios  3.97          Economics           Yes
1    55            Ian Brown  1.44  Political Science            No
2    54         Stanley Dean  3.75         Philosophy           Yes
3    19  Stephanie Henderson  1.86        Mathematics            No
4    81          Angela Mora  3.86            Physics           Yes
..   ..                  ...   ...                ...           ...
96   20          Diane Brown  1.73        Mathematics            No
97   41     Brenda Valentine  3.10            Physics            No
98   86        Grace Hoffman  1.30          Chemistry            No
100  61      Samantha Steele  2.56            Spanish            No
101  22            Lisa Chen  1.45                Art            No

[95 rows x 5 columns]

In [ ]:
#12) Load “tuition.xlsx” into a dataframe called “df2”
df2= pd.read_excel('C:/Users/rupas/Desktop/Applied Business Statistics/Python4Statistics/Stuff For Class/Homework Assignments/Assignment 1/tuition.xlsx', engine='openpyxl')

In [13]:
#13)	 Check df2 for duplicates and display them if they exist
duplicates = df2.duplicated()
print(duplicates)

#View instances of the duplicated rows
duplicated_rows = df2[df2.duplicated()]
print(duplicated_rows)

0      False
1      False
2      False
3      False
4      False
       ...
96     False
97     False
98     False
99     False
100    False
Length: 101, dtype: bool
    ID       Name State Resident  Tuition  Financial Aid
31  55  Ian Brown            Yes    20000           6977

In [14]:
#14) Drop any duplicate rows from the df2 and redisplay duplicate rows to check that they’ve been removed
df2.drop_duplicates(inplace=True)
duplicated_rows2 = df2[df2.duplicated()]
print(duplicated_rows2)

Empty DataFrame
Columns: [ID, Name, State Resident, Tuition, Financial Aid]
Index: []

In [15]:
#15)	Check df2 for rows with missing values and display them if they exist
print(df2.isnull().sum())

missing_data = df2[df2.isna().any(axis=1)]
print(missing_data)

ID                0
Name              0
State Resident    0
Tuition           0
Financial Aid     0
dtype: int64
Empty DataFrame
Columns: [ID, Name, State Resident, Tuition, Financial Aid]
Index: []

In [16]:
#16)	Drop any rows with missing values from the dataset and redisplay the rows with missing values to check that they’ve been removed  

#Since there is no missing values in any rows we don't have to drop any row.

In [17]:
#17)	Create a column called “Cost” that is the result of subtracting financial aid from tuition.

df2["Cost"] = df2["Tuition"] - df2["Financial Aid"]
df2

     ID                 Name State Resident  Tuition  Financial Aid   Cost
0    17      Alexandra Green            Yes    20000           5180  14820
1    18      Alexandra Green             No    30000           7087  22913
2    81          Angela Mora            Yes    20000          12031   7969
3    57        Angela Oneill            Yes    20000           7064  12936
4     2     Anthony Martinez            Yes    20000           6479  13521
..   ..                  ...            ...      ...            ...    ...
96   90  Stephanie Stevenson            Yes    20000          13431   6569
97   42         Summer Baker            Yes    20000          12094   7906
98   43          Tamara Lowe            Yes    20000           5761  14239
99   78     William Caldwell             No    30000          10663  19337
100  11      William Stewart            Yes    20000           9349  10651

[100 rows x 6 columns]

In [18]:
#18)	Merge the two dataframes into a new dataframe called “df3” using an inner join on the “ID” column

df3 = pd.merge(df1, df2, on="ID", how="inner")
df3

,ID,Name_x,GPA,Major,Honor Student,Name_y,State Resident,Tuition,Financial Aid,Cost
0,23,Rose Rios,3.97,Economics,Yes,Rose Rios,Yes,20000,11038,8962
1,55,Ian Brown,1.44,Political Science,No,Ian Brown,Yes,20000,6977,13023
2,54,Stanley Dean,3.75,Philosophy,Yes,Stanley Dean,Yes,20000,11481,8519
3,19,Stephanie Henderson,1.86,Mathematics,No,Stephanie Henderson,Yes,20000,6373,13627
4,81,Angela Mora,3.86,Physics,Yes,Angela Mora,Yes,20000,12031,7969
...,...,...,...,...,...,...,...,...,...,...
90,20,Diane Brown,1.73,Mathematics,No,Diane Brown,No,30000,11660,18340
91,41,Brenda Valentine,3.10,Physics,No,Brenda Valentine,No,30000,9915,20085
92,86,Grace Hoffman,1.30,Chemistry,No,Grace Hoffman,No,30000,12102,17898
93,61,Samantha Steele,2.56,Spanish,No,Samantha Steele,No,30000,13103,16897
94,22,Lisa Chen,1.45,Art,No,Lisa Chen,No,30000,9901,20099

In [19]:
#19)	Rename the “Name_x” column “Full Name” using a dictionary
rename_dict = {
    "Name_x": "Full Name"
}
#rename columns using the dictionary
df3.rename(columns=rename_dict, inplace=True)
df3

,ID,Full Name,GPA,Major,Honor Student,Name_y,State Resident,Tuition,Financial Aid,Cost
0,23,Rose Rios,3.97,Economics,Yes,Rose Rios,Yes,20000,11038,8962
1,55,Ian Brown,1.44,Political Science,No,Ian Brown,Yes,20000,6977,13023
2,54,Stanley Dean,3.75,Philosophy,Yes,Stanley Dean,Yes,20000,11481,8519
3,19,Stephanie Henderson,1.86,Mathematics,No,Stephanie Henderson,Yes,20000,6373,13627
4,81,Angela Mora,3.86,Physics,Yes,Angela Mora,Yes,20000,12031,7969
...,...,...,...,...,...,...,...,...,...,...
90,20,Diane Brown,1.73,Mathematics,No,Diane Brown,No,30000,11660,18340
91,41,Brenda Valentine,3.10,Physics,No,Brenda Valentine,No,30000,9915,20085
92,86,Grace Hoffman,1.30,Chemistry,No,Grace Hoffman,No,30000,12102,17898
93,61,Samantha Steele,2.56,Spanish,No,Samantha Steele,No,30000,13103,16897
94,22,Lisa Chen,1.45,Art,No,Lisa Chen,No,30000,9901,20099

In [20]:
#20)	Drop / remove the redundant  “Name_y” column from df3
df3.drop(columns=['Name_y'], inplace=True)
print(df3)

    ID            Full Name   GPA              Major Honor Student  \
0   23            Rose Rios  3.97          Economics           Yes
1   55            Ian Brown  1.44  Political Science            No
2   54         Stanley Dean  3.75         Philosophy           Yes
3   19  Stephanie Henderson  1.86        Mathematics            No
4   81          Angela Mora  3.86            Physics           Yes
..  ..                  ...   ...                ...           ...
90  20          Diane Brown  1.73        Mathematics            No
91  41     Brenda Valentine  3.10            Physics            No
92  86        Grace Hoffman  1.30          Chemistry            No
93  61      Samantha Steele  2.56            Spanish            No
94  22            Lisa Chen  1.45                Art            No

   State Resident  Tuition  Financial Aid   Cost
0             Yes    20000          11038   8962
1             Yes    20000           6977  13023
2             Yes    20000          11481   8519
3             Yes    20000           6373  13627
4             Yes    20000          12031   7969
..            ...      ...            ...    ...
90             No    30000          11660  18340
91             No    30000           9915  20085
92             No    30000          12102  17898
93             No    30000          13103  16897
94             No    30000           9901  20099

[95 rows x 9 columns]

In [21]:
#21)	Create a “First Name” and “Last Name” column by splitting the “Full Name” column
df3['Full Name'] = df3['Full Name'].astype(str)

df3[['First Name','Last Name']] = df3['Full Name'].str.split(n=1, expand=True)
print(df3)

    ID            Full Name   GPA              Major Honor Student  \
0   23            Rose Rios  3.97          Economics           Yes
1   55            Ian Brown  1.44  Political Science            No
2   54         Stanley Dean  3.75         Philosophy           Yes
3   19  Stephanie Henderson  1.86        Mathematics            No
4   81          Angela Mora  3.86            Physics           Yes
..  ..                  ...   ...                ...           ...
90  20          Diane Brown  1.73        Mathematics            No
91  41     Brenda Valentine  3.10            Physics            No
92  86        Grace Hoffman  1.30          Chemistry            No
93  61      Samantha Steele  2.56            Spanish            No
94  22            Lisa Chen  1.45                Art            No

   State Resident  Tuition  Financial Aid   Cost First Name  Last Name
0             Yes    20000          11038   8962       Rose       Rios
1             Yes    20000           6977  13023        Ian      Brown
2             Yes    20000          11481   8519    Stanley       Dean
3             Yes    20000           6373  13627  Stephanie  Henderson
4             Yes    20000          12031   7969     Angela       Mora
..            ...      ...            ...    ...        ...        ...
90             No    30000          11660  18340      Diane      Brown
91             No    30000           9915  20085     Brenda  Valentine
92             No    30000          12102  17898      Grace    Hoffman
93             No    30000          13103  16897   Samantha     Steele
94             No    30000           9901  20099       Lisa       Chen

[95 rows x 11 columns]

In [22]:
#22)	Group the students by major and display the mean GPA and mean net cost by major
group1 = df3.groupby(['Major']).aggregate({'GPA':['mean'],'Tuition':['mean']})
print(group1)

                        GPA       Tuition
                       mean          mean
Major
Art                2.833333  22000.000000
Biology            2.586667  22222.222222
Business           2.051667  23333.333333
Chemistry          2.652000  24000.000000
Economics          3.970000  20000.000000
English            2.722500  23750.000000
History            2.567273  21818.181818
Mathematics        1.676667  25000.000000
Philosophy         2.684000  24000.000000
Physics            2.345000  25000.000000
Political Science  1.440000  20000.000000
Spanish            2.235455  21818.181818
Theatre            2.300000  22500.000000

In [23]:
#23)	Filter out everyone with a GPA below a 2.0 from df3 
below2 = df3[df3['GPA'] < 2.0]
below2.head()

,ID,Full Name,GPA,Major,Honor Student,State Resident,Tuition,Financial Aid,Cost,First Name,Last Name
1,55,Ian Brown,1.44,Political Science,No,Yes,20000,6977,13023,Ian,Brown
3,19,Stephanie Henderson,1.86,Mathematics,No,Yes,20000,6373,13627,Stephanie,Henderson
5,60,Mark Martin,1.47,Chemistry,No,Yes,20000,12477,7523,Mark,Martin
7,11,William Stewart,1.27,Biology,No,Yes,20000,9349,10651,William,Stewart
18,39,Patrick Thomas,1.98,History,No,Yes,20000,12634,7366,Patrick,Thomas

In [24]:
#24)	Sort df3 by ID in descending order

id_desc = df3.sort_values('ID', ascending=False)
print(id_desc)

     ID           Full Name   GPA        Major Honor Student State Resident  \
78  100  Lawrence Rodriguez  2.66      Theatre            No            Yes
65   99        Mary Sampson  3.43          Art            No            Yes
11   98      Donald Blevins  3.52      Theatre           Yes            Yes
72   97        Linda Dalton  1.30      Spanish            No            Yes
29   96        Jamie Knight  1.65     Business            No             No
..  ...                 ...   ...          ...           ...            ...
62    5      Chelsea Flores  3.01    Chemistry            No            Yes
46    4          Eric Ellis  1.20  Mathematics            No             No
38    3       Shawn Gilbert  1.85     Business            No            Yes
75    2    Anthony Martinez  2.86      History            No            Yes
51    1        Nicole Allen  3.17      Biology            No            Yes

    Tuition  Financial Aid   Cost First Name  Last Name
78    20000          13674   6326   Lawrence  Rodriguez
65    20000           8653  11347       Mary    Sampson
11    20000          12147   7853     Donald    Blevins
72    20000          11388   8612      Linda     Dalton
29    30000           9843  20157      Jamie     Knight
..      ...            ...    ...        ...        ...
62    20000           9534  10466    Chelsea     Flores
46    30000          12978  17022       Eric      Ellis
38    20000          14750   5250      Shawn    Gilbert
75    20000           6479  13521    Anthony   Martinez
51    20000           9677  10323     Nicole      Allen

[95 rows x 11 columns]

In [25]:
#25)	Export df3 as a CSV file and as an Excel file.  Do not export with an index column.

#exporting as CSV file
df3.to_csv('output.csv', index=False)

#exporting as Excel file
df3.to_excel('output.xlsx', index=False)