#Homework for Chapter 1 and 2

In [1]:
###Load the data from csv file Salaries.csv in a dataframe. for eg :df = pd.read_csv('your_path/Salaries.csv')
import pandas as pd

salaries_dataset = pd.read_csv('D:/Webster University/Assignments/Spring 2024/Spring 1/Analytics Using Python/Assignment/Salaries.csv')
salaries_dataset

C:\Users\rupas\AppData\Local\Temp\ipykernel_14256\781467883.py:4: DtypeWarning: Columns (3,4,5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  salaries_dataset = pd.read_csv('D:/Webster University/Assignments/Spring 2024/Spring 1/Analytics Using Python/Assignment/Salaries.csv')

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

In [2]:
### View the first few rows
salaries_dataset.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [3]:
###Explore the data using info(), describe()

In [4]:
salaries_dataset.info()
salaries_dataset.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

                  Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

In [5]:
###What is the average BasePay

salaries_dataset['BasePay']=pd.to_numeric(salaries_dataset['BasePay'], errors='coerce')
average_basepay = salaries_dataset['BasePay'].mean()
average_basepay

66325.4488404877

In [6]:
###What is the highest amount of OvertimePay in the dataset

salaries_dataset['OvertimePay']=pd.to_numeric(salaries_dataset['OvertimePay'], errors='coerce')
highest_overtime_pay = salaries_dataset['OvertimePay'].max()
highest_overtime_pay

245131.88

In [18]:
###How many unique job titles are there
salaries_dataset['JobTitle']=salaries_dataset['JobTitle'].astype('str')
unique_job_titles = salaries_dataset['JobTitle'].unique()
print("List of unique job titles: ", unique_job_titles)
print("Total unique job titles: ",salaries_dataset['JobTitle'].nunique())

List of unique job titles:  ['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY'
 'CAPTAIN III (POLICE DEPARTMENT)' 'WIRE ROPE CABLE MAINTENANCE MECHANIC'
 ... 'Conversion' 'Cashier 3' 'Not provided']
Total unique job titles:  2159

In [19]:
###Use the .query method to find rows where OvertimePay is greater than 1500. Display the result 

higher_overtimepay = salaries_dataset.query('OvertimePay > 1500')
higher_overtimepay

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146022,146023,Gary S Weiner,Publ Svc Aide-Asst to Prof,2690.87,1594.77,178.94,0.00,4464.58,4464.58,2014,NaN,San Francisco,PT
146064,146065,Amy Zhen,Publ Svc Aide-Asst to Prof,2619.46,1614.10,80.00,43.13,4313.56,4356.69,2014,NaN,San Francisco,PT
146098,146099,Hla H Win,Junior Clerk,2504.00,1731.28,0.00,42.36,4235.28,4277.64,2014,NaN,San Francisco,PT
146099,146100,Emilio Benedetti,Junior Clerk,2702.77,1531.27,0.00,42.34,4234.04,4276.38,2014,NaN,San Francisco,PT
146142,146143,Esteban Farfan,Junior Clerk,2602.99,1538.60,0.00,41.42,4141.59,4183.01,2014,NaN,San Francisco,PT

In [21]:
# with .loc method
highest_overtime_pay = salaries_dataset.loc[salaries_dataset.OvertimePay > 1500]
highest_overtime_pay

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146022,146023,Gary S Weiner,Publ Svc Aide-Asst to Prof,2690.87,1594.77,178.94,0.00,4464.58,4464.58,2014,NaN,San Francisco,PT
146064,146065,Amy Zhen,Publ Svc Aide-Asst to Prof,2619.46,1614.10,80.00,43.13,4313.56,4356.69,2014,NaN,San Francisco,PT
146098,146099,Hla H Win,Junior Clerk,2504.00,1731.28,0.00,42.36,4235.28,4277.64,2014,NaN,San Francisco,PT
146099,146100,Emilio Benedetti,Junior Clerk,2702.77,1531.27,0.00,42.34,4234.04,4276.38,2014,NaN,San Francisco,PT
146142,146143,Esteban Farfan,Junior Clerk,2602.99,1538.60,0.00,41.42,4141.59,4183.01,2014,NaN,San Francisco,PT

In [ ]:
###Optional : Use the .loc method to get the above result

In [26]:
### Sort the data for each Year for the TotalPay in ascending order 
salaries_dataset.sort_values('TotalPay', ascending=True).head(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT
106741,106742,Ronald Hill,Recreation Director,NaN,0.0,0.0,7959.18,0.00,7959.18,2013,NaN,San Francisco,NaN
106743,106744,Germond J Gray,Recreation Director,NaN,0.0,0.0,7959.18,0.00,7959.18,2013,NaN,San Francisco,NaN
106745,106746,Tiffany M Rasso,Recreation Director,NaN,0.0,0.0,7959.18,0.00,7959.18,2013,NaN,San Francisco,NaN
106746,106747,Bertha Robinson,Transit Operator,NaN,0.0,0.0,7959.18,0.00,7959.18,2013,NaN,San Francisco,NaN

In [28]:
###Which Job title has the highest TotalPay

highest_pay = salaries_dataset[['JobTitle','TotalPay']].max()
highest_pay

JobTitle    ZOO CURATOR
TotalPay      567595.43
dtype: object

In [33]:
###What is the average (mean) BasePay of all employees per year? (2011-2014
average_base_pay = salaries_dataset.groupby('Year')['BasePay'].mean()
average_base_pay

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [ ]:
### Save the file and upload